package model;

// Generated May 2, 2014 10:14:12 AM by Hibernate Tools 3.4.0.CR1


import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Anggota generated by hbm2java
 */
@Entity
@Table(name = "anggota")
@ManagedBean
@SessionScoped
public class Anggota implements java.io.Serializable {

	private String barcode;
	private String idAnggota;
	private String namaLengkap;


	public Anggota() {
	}

	public Anggota(String barcode, String idAnggota) {
		this.barcode = barcode;
		this.idAnggota = idAnggota;
	}

	public Anggota(String barcode, String idAnggota, String namaLengkap) {
		this.barcode = barcode;
		this.idAnggota = idAnggota;
		this.namaLengkap = namaLengkap;

	}

	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	public String getIdAnggota() {
		return this.idAnggota;
	}

	public void setIdAnggota(String idAnggota) {
		this.idAnggota = idAnggota;
	}

	public String getNamaLengkap() {
		return this.namaLengkap;
	}

	public void setNamaLengkap(String namaLengkap) {
		this.namaLengkap = namaLengkap;
	}

}
