package model;

// Generated May 2, 2014 10:14:12 AM by Hibernate Tools 3.4.0.CR1

/**
 * KendaraanOperasional generated by hbm2java
 */
public class KendaraanOperasional implements java.io.Serializable {

	private Integer idKendaraan;
	private String noPolisi;
	private String keteranganKendaraan;

	public KendaraanOperasional() {
	}

	public KendaraanOperasional(String noPolisi, String keteranganKendaraan) {
		this.noPolisi = noPolisi;
		this.keteranganKendaraan = keteranganKendaraan;
	}

	public Integer getIdKendaraan() {
		return this.idKendaraan;
	}

	public void setIdKendaraan(Integer idKendaraan) {
		this.idKendaraan = idKendaraan;
	}

	public String getNoPolisi() {
		return this.noPolisi;
	}

	public void setNoPolisi(String noPolisi) {
		this.noPolisi = noPolisi;
	}

	public String getKeteranganKendaraan() {
		return this.keteranganKendaraan;
	}

	public void setKeteranganKendaraan(String keteranganKendaraan) {
		this.keteranganKendaraan = keteranganKendaraan;
	}

}
