package model;

// Generated May 2, 2014 10:14:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log implements java.io.Serializable {

	private int idlog;
	private String kejadian;
	private String deskripsi;
	private Date tanggalKejadian;

	public Log() {
	}

	public Log(int idlog, String kejadian, String deskripsi,
			Date tanggalKejadian) {
		this.idlog = idlog;
		this.kejadian = kejadian;
		this.deskripsi = deskripsi;
		this.tanggalKejadian = tanggalKejadian;
	}

	public int getIdlog() {
		return this.idlog;
	}

	public void setIdlog(int idlog) {
		this.idlog = idlog;
	}

	public String getKejadian() {
		return this.kejadian;
	}

	public void setKejadian(String kejadian) {
		this.kejadian = kejadian;
	}

	public String getDeskripsi() {
		return this.deskripsi;
	}

	public void setDeskripsi(String deskripsi) {
		this.deskripsi = deskripsi;
	}

	public Date getTanggalKejadian() {
		return this.tanggalKejadian;
	}

	public void setTanggalKejadian(Date tanggalKejadian) {
		this.tanggalKejadian = tanggalKejadian;
	}

}
