package model;

// Generated May 2, 2014 10:14:12 AM by Hibernate Tools 3.4.0.CR1

/**
 * Opsi generated by hbm2java
 */
public class Opsi implements java.io.Serializable {

	private Integer idopsi;
	private String namaOpsi;
	private String nilaiOpsi;

	public Opsi() {
	}

	public Opsi(String namaOpsi, String nilaiOpsi) {
		this.namaOpsi = namaOpsi;
		this.nilaiOpsi = nilaiOpsi;
	}

	public Integer getIdopsi() {
		return this.idopsi;
	}

	public void setIdopsi(Integer idopsi) {
		this.idopsi = idopsi;
	}

	public String getNamaOpsi() {
		return this.namaOpsi;
	}

	public void setNamaOpsi(String namaOpsi) {
		this.namaOpsi = namaOpsi;
	}

	public String getNilaiOpsi() {
		return this.nilaiOpsi;
	}

	public void setNilaiOpsi(String nilaiOpsi) {
		this.nilaiOpsi = nilaiOpsi;
	}

}
