package model;

// Generated May 2, 2014 10:14:12 AM by Hibernate Tools 3.4.0.CR1

/**
 * TransaksiAnggota generated by hbm2java
 */
public class TransaksiAnggota implements java.io.Serializable {

	private int idHistory;
	private Anggota anggota;
	private Transaksi transaksi;

	public TransaksiAnggota() {
	}

	public TransaksiAnggota(int idHistory) {
		this.idHistory = idHistory;
	}

	public TransaksiAnggota(int idHistory, Anggota anggota, Transaksi transaksi) {
		this.idHistory = idHistory;
		this.anggota = anggota;
		this.transaksi = transaksi;
	}

	public int getIdHistory() {
		return this.idHistory;
	}

	public void setIdHistory(int idHistory) {
		this.idHistory = idHistory;
	}

	public Anggota getAnggota() {
		return this.anggota;
	}

	public void setAnggota(Anggota anggota) {
		this.anggota = anggota;
	}

	public Transaksi getTransaksi() {
		return this.transaksi;
	}

	public void setTransaksi(Transaksi transaksi) {
		this.transaksi = transaksi;
	}

}
